// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentDocuments() {
  return window['go']['main']['App']['GetRecentDocuments']();
}

export function QueryDocuments(arg1) {
  return window['go']['main']['App']['QueryDocuments'](arg1);
}
